name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other commands here
        echo This runs in a shell
    - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install pytest pytest-md pytest-emoji
    - name: Run pytest
      uses: pavelzw/pytest-action@v2
      with:
        verbose: true
        emoji: true
        job-summary: true
        custom-arguments: '-q'
        click-to-expand: true
        report-title: 'Test Report'